# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "onnx"
SPDX-PackageSupplier = "onnx-technical-discuss@lists.lfaidata.foundation"
SPDX-PackageDownloadLocation = "onnx.ai"

[[annotations]]
path = "codecov.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".github/**/**.md", ".github/pull_request_template.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**/**.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/simple/**/test_data_set_0/**pb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/node/**/test_data_set_0/**.pb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/simple/**/**.onnx"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/pytorch-operator/**/test_data_set_0/**.pb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/pytorch-operator/**/**.onnx"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/pytorch-operator/**/**.pb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/node/**/**.onnx"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/pytorch-converted/**/test_data_set_0/**.pb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/light/**.onnx"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/light/**.pb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/real/**/**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/pytorch-converted/**/**.onnx"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/backend/test/data/light/light/**.onnx"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["onnx/onnx-operators**", "onnx/onnx-ml**", "onnx/onnx-data**", "onnx/onnx**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/docsgen/source/api/**md", "docs/docsgen/source/_static/**", "docs/docsgen/source/requirements.txt", "docs/docsgen/source/onnx-favicon.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/Change**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/Test**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/Operator**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".gitignore", "**/**/.gitignore", ".gitmodules", ".lintrunner.toml", ".gitattributes", ".git-blame-ignore-revs", ".clang**", ".editorconfig"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/docsgen/source/intro/images/**", "docs/docsgen/source/intro/**md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["examples/**ipynb", "examples/resources/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["MANIFEST.in", "VERSION_NUMBER", "CODE_OF_CONDUCT.md", "CODEOWNERS", "pyproject**.toml", "requirements**.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["onnx/onnx_cpp2py_export/**pyi", "onnx/py.typed"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["onnx/defs/**/**.cc", "onnx/defs/**/**.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "onnx/reference/ops/aionnxml/**py"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["onnx/defs/**.cc", "onnx/defs/**.h"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["cmake/ONNXConfig**.in", "CMakeLists.txt", "cmake/**cmake", "cmake/"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".vscode/settings.json", "docs/docsgen/source/_templates/layout.html", "docs/docsgen/source/_templates/sidebar-nav-bs.html", "docs/images/onnx_hub_arch.svg", "docs/onnx-horizontal-color.png", "tools/protoc-gen-mypy.sh.in"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["onnx/gen_proto.py", "tools/protoc-gen-mypy.bat", "onnx/reference/op_run.py"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["onnx/backend/sample/ops/abs.py", "onnx/gen_proto.py"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/proposals/images/composing_broadcast_axes.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"
