# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: PR Checks Comment

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

permissions:
  contents: read

jobs:
  suggest-changes:
    name: Suggest fixes
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download PR number artifact
        id: download-pr
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        continue-on-error: true
        with:
          name: pr-artifacts
          path: /tmp/pr_artifacts/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR number
        if: steps.download-pr.outcome == 'success'
        id: pr
        run: echo "number=$(cat /tmp/pr_artifacts/pr_number)" >> "$GITHUB_OUTPUT"
      - name: Check if diff is empty
        if: steps.download-pr.outcome == 'success'
        id: diff
        run: |
          if [ -s /tmp/pr_artifacts/lintrunner.diff ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Checkout PR
        if: steps.download-pr.outcome == 'success' && steps.diff.outputs.has_changes == 'true'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: refs/pull/${{ steps.pr.outputs.number }}/head
          persist-credentials: false
      - name: Apply lintrunner fixes
        if: steps.download-pr.outcome == 'success' && steps.diff.outputs.has_changes == 'true'
        run: git apply /tmp/pr_artifacts/lintrunner.diff
      - name: Suggest changes
        if: steps.download-pr.outcome == 'success' && steps.diff.outputs.has_changes == 'true'
        uses: parkerbxyz/suggest-changes@bd099ea0d10f0e9efeb9e46d604bbe6d7a80bc34
        with:
          comment: 'You can commit the suggested changes from lintrunner.'
